baseURL = "http://christianfjung.me/PersonalSite"
canonifyURLs = true
languageCode = "en-us"
title = "Christian F. Jung"
theme= "hallo"
publishDir="docs"

[Author]
    name = "Christian F. Jung"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:christianfjung@gmail.com"

   # [[params.links]]
    #  icon = "github"
     #  title = "Github"
      #  url = "https://github.com/christianfjung"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/christianfjung"

    [[params.links]]
        icon = "linkedin"
        title = "Linked In"
        url = "https://linkedin.com/in/christianfjung"

  [[params.links]]
        iconset = "fas"
        icon = "file-download"
        title = "Resume"
        url = "images/resume.pdf"